### ISSUE TITLE
URL-Parameters are not available in the msg for use with functions

### ISSUE THREAD

**Issue by yetility** [bmdevx/node-red-contrib-http-instance#2]
It would be nice if URL-Parameters are available in msg.

ex.: URL in Browser=http://127.0.0.1:1880/test?min=2&max=10
In this case the URL to react on have to be "http://127.0.0.1:1880/test" (without any parameters) and msg.min=2 and msg.max=10 should return there values on the output.

**Comment by bmdevx** [comment]
Due to how message responses are processed and the possibility of a query overwriting a necessary attribute the msg object, setting the message with a query parameter can not be done. All query parameters are available within the msg.payload object as well within msg.req.params or msg.req.query objects. If you would like to have a msg object with a direct attribute such as above then you can always have a node set the msg.payload as the msg object.
